[package]
name = "interactor-bybit-exchange"
version.workspace = true
edition.workspace = true

[dependencies]
interactor-exchange-api = { workspace = true }
domain-model = { workspace = true }
storage-core-api = { workspace = true }
engine-core-api = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
async-trait = { workspace = true }
anyhow = { worksapce = true }
tokio = { workspace = true }
chrono = { workspace = true }
tracing = { workspace = true }
eac = { workspace = true }
uuid = { workspace = true }
