//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "tick")]
pub struct Model {
    #[sea_orm(
    primary_key,
    auto_increment = false,
    column_type = "Binary(BlobSize::Blob(Some(16)))"
    )]
    pub id: Vec<u8>,
    pub timestamp: DateTimeUtc,
    pub exchange: String,
    pub market_type: String,
    pub source_currency: String,
    pub target_currency: String,
    #[sea_orm(column_type = "Float")]
    pub price: f32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
