[package]
name = "interactor-rest-client"
version.workspace = true
edition.workspace = true

[dependencies]
interactor-core-api = { workspace = true }
domain-model = { workspace = true }
interactor-rest-api = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_urlencoded = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
async-trait = { workspace = true }
