[package]
name = "plugin-loader"
version.workspace = true
edition.workspace = true

[dependencies]
plugin-api = { workspace = true }
libloading = { workspace = true }
tempfile = { workspace = true }
anyhow = { workspace = true }
