[package]
name = "simulator-core-api"
version.workspace = true
edition.workspace = true

[dependencies]
domain-model = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
async-trait = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
