[workspace]
members = [
    "common/eac",
    "common/strategy-api",
    "common/domain-model",
    "common/synapse",
    "common/indicators-calculation",
    "common/indicators-api",
    "common/plugin-loader",
    "standalone",
    "interactor/app",
    "interactor/core",
    "interactor/config",
    "interactor/rest-api",
    "interactor/rest-client",
    "storage/app",
    "storage/core",
    "storage/migration",
    "storage/rest-api",
    "storage/rest-client",
    "engine/app",
    "engine/core",
    "engine/rest-api",
    "engine/rest-client",
    "simulator/app",
    "simulator/core",
    "simulator/rest-api",
    "simulator/rest-client",
    "registry/app",
    "registry/core",
    "registry/rest-api",
    "registry/rest-client",
    "plugins/test",
    "plugins/simulation-e2e",
]

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
domain-model = { path = "common/domain-model" }
eac = { path = "common/eac" }
indicators-api = { path = "common/indicators-api" }
indicators-calculation = { path = "common/indicators-calculation" }
plugin-loader = { path = "common/plugin-loader" }
strategy-api = { path = "common/strategy-api" }
synapse = { path = "common/synapse" }

engine-app = { path = "engine/app" }
engine-core = { path = "engine/core" }
engine-rest-api = { path = "engine/rest-api" }
engine-rest-client = { path = "engine/rest-client" }

interactor-app = { path = "interactor/app" }
interactor-config = { path = "interactor/config" }
interactor-core = { path = "interactor/core" }
interactor-rest-api = { path = "interactor/rest-api" }
interactor-rest-client = { path = "interactor/rest-client" }

registry-app = { path = "registry/app" }
registry-core = { path = "registry/core" }
registry-rest-api = { path = "registry/rest-api" }
registry-rest-client = { path = "registry/rest-client" }

simulator-app = { path = "simulator/app" }
simulator-core = { path = "simulator/core" }
simulator-rest-api = { path = "simulator/rest-api" }
simulator-rest-client = { path = "simulator/rest-client" }

storage-app = { path = "storage/app" }
storage-core = { path = "storage/core" }
storage-rest-api = { path = "storage/rest-api" }
storage-rest-client = { path = "storage/rest-client" }

rdkafka = { version = "0.29.0", features = ["cmake-build"] }
tokio = { version = "1.28.0", features = ["full"] }
futures = "0.3.28"
uuid = { version = "1.3.2", features = ["v4", "serde"] }
chrono = "0.4.24"
serde = { verion = "1.0.162", features = ["derive", "serde_derive"] }
serde_json = "1.0"
serde-inline-default = "0.1.1"
serde_urlencoded = "0.7.1"
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.17", features = ["env-filter"] }
tracing-appender = "0.2.2"
sea-orm = { version = "0.11.3", features = ["sqlx-mysql", "runtime-async-std-native-tls", "macros"] }
config = { verion = "0.13.3", features = ["yaml"] }
once_cell = "1.17.1"
axum = { version = "0.6.18", features = ["macros", "multipart"] }
hyper = { version = "1.0.0-rc.3", features = ["full"] }
anyhow = "1.0.71"
reqwest = { version = "0.11", features = ["json", "blocking"] }
async-trait = "0.1.68"
nanoid = "0.4.0"
libloading = "0.8"
tempfile = "3.6.0"
crossbeam-channel = "0.5.8"
lazy_static = "1.4.0"
thiserror = "1.0.40"
http = "0.2.9"
ring = "0.16.20"
fehler = "1.0.0"
derive_builder = "0.12.0"
tungstenite = { version = "0.19.0", features = ["native-tls"] }
url = "2.1.0"
base64 = "0.21.0"
sha2 = "0.10.6"
hmac = "0.12.1"
async-std = { version = "1", features = ["attributes", "tokio1"] }
sea-orm-migration = { version = "0.11.0", features = ["sqlx-mysql", "runtime-async-std-native-tls"] }
