---
version: "3.7"
name: ncn-${NAMESPACE}

networks:
  tailscale_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.${SUBNET_ID}.0.0/16
          gateway: 172.${SUBNET_ID}.0.10
  db_network:
    driver: bridge

services:
  engine:
    image: engine:${TAG}
    environment:
      ENGINE_INTERACTOR_URL: interactor:8083
      ENGINE_REGISTRY_URL: registry:8085
      ENGINE_STORAGE_URL: storage:8082
    networks:
      tailscale_network:
        ipv4_address: 172.${SUBNET_ID}.0.2
      db_network:
    depends_on:
      - tailscale
      - db
    restart: unless-stopped
  interactor:
    image: interactor:${TAG}
    environment:
      INTERACTOR_STORAGE_URL: storage:8082
      INTERACTOR_ENGINE_URL: engine:8081
      INTERACTOR_EAC_DEMO: ${DEMO}
      INTERACTOR_EAC_EXCHANGES_OKX_AUTH_KEY: ${OKX_API_KEY}
      INTERACTOR_EAC_EXCHANGES_OKX_AUTH_PASSPHRASE: ${OKX_API_PASSPHRASE}
      INTERACTOR_EAC_EXCHANGES_OKX_AUTH_SECRET: ${OKX_API_SECRET}
    networks:
      tailscale_network:
        ipv4_address: 172.${SUBNET_ID}.0.3
      db_network:
    depends_on:
      - tailscale
      - db
    restart: unless-stopped
  registry:
    image: registry:${TAG}
    environment:
      REGISTRY_ENGINE_URL: engine:8081
    networks:
      tailscale_network:
        ipv4_address: 172.${SUBNET_ID}.0.4
      db_network:
    depends_on:
      - tailscale
      - db
    restart: unless-stopped
  simulator:
    image: simulator:${TAG}
    environment:
      SIMULATOR_DATABASE_URL: postgres://postgres:root@db:5432
      SIMULATOR_ENGINE_URL: engine:8081
      SIMULATOR_STORAGE_URL: storage:8082
      SIMULATOR_INTERACTOR_URL: interactor:8083
    networks:
      tailscale_network:
        ipv4_address: 172.${SUBNET_ID}.0.5
      db_network:
    depends_on:
      - tailscale
      - db
    restart: unless-stopped
  storage:
    image: storage:${TAG}
    environment:
      STORAGE_DATABASE_URL: postgres://postgres:root@db:5432
      STORAGE_INTERACTOR_URL: interactor:8083
    networks:
      tailscale_network:
        ipv4_address: 172.${SUBNET_ID}.0.6
      db_network:
    depends_on:
      - tailscale
      - db
    restart: unless-stopped
  ui:
    image: ui:${TAG}
    environment:
      UI_SIMULATOR_URL: simulator:8084
      UI_STORAGE_URL: storage:8082
    networks:
      tailscale_network:
        ipv4_address: 172.${SUBNET_ID}.0.7
      db_network:
    depends_on:
      - tailscale
      - db
    restart: unless-stopped

  # capability providers
  tailscale:
    image: tailscale/tailscale:stable
    hostname: ncn-${NAMESPACE}
    environment:
      TS_AUTHKEY: ${TS_AUTHKEY}
      # in case of external access, don't forget to approve subnet in tailscale admin console
      TS_EXTRA_ARGS: "--advertise-routes=172.${SUBNET_ID}.0.0/16"
    networks:
      - tailscale_network
    volumes:
      - /dev/net/tun:/dev/net/tun
      - /var/lib/tailscale:/var/lib/tailscale
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    privileged: true
    restart: unless-stopped
  db:
    image: postgres:13.2
    environment:
      POSTGRES_PASSWORD: root
    networks:
      tailscale_network:
        ipv4_address: 172.${SUBNET_ID}.0.11
      db_network:
    restart: unless-stopped
