[package]
name = "simulator-persistence-api"
version.workspace = true
edition.workspace = true

[dependencies]
simulator-core-api = { workspace = true }
anyhow = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }
chrono = { workspace = true }
