[package]
name = "storage-rest-client"
version.workspace = true
edition.workspace = true

[dependencies]
domain-model = { workspace = true }
storage-rest-api = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_urlencoded = { workspace = true }
tracing = { workspace = true }
