[package]
name = "ui-app"
version.workspace = true
edition.workspace = true

[dependencies]
ui-config = { workspace = true }
ui-core = { workspace = true }
ui-rest-api-server = { workspace = true }
domain-model = { workspace = true }
simulator-rest-client = { workspace = true }
storage-rest-client = { workspace = true }
ui-charming-builder = { workspace = true }
indicators = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
config = { workspace = true }
axum = { workspace = true }
once_cell = { workspace = true }
