steps:
  - key: "check"
    label: ":mag: Check"
    commands:
      - "cargo clippy -- -D warnings"
    plugins:
      - docker#v5.8.0:
          image: "rust-image"
      - cache#v0.6.0:
          paths:
          - "target"
          - "/usr/local/cargo"
          restore: "branch"
          save: "branch"
  - key: "build_binaries"
    depends_on: "check"
    allow_dependency_failure: true #todo remove
    label: ":hammer_and_wrench: Build binaries"
    commands:
      - "cargo build --release"
      - "find ./target/release -type f \\( -name '.*' -or -name '*.d' -or -name '*.rlib' \\) -delete"
    artifact_paths:
      - "target/release/*"
    plugins:
      - docker#v5.8.0:
          image: "rust-image"
      - cache#v0.6.0:
          paths:
            - "target"
            - "/usr/local/cargo"
          restore: "branch"
          save: "branch"
  - key: "test"
    depends_on: "build_binaries"
    label: ":clipboard: Test"
    commands:
      - "cargo nextest run --no-capture --release"
    plugins:
      - docker#v5.8.0:
          image: "rust-image"
      - cache#v0.6.0:
          paths:
            - "target"
            - "/usr/local/cargo"
          restore: "branch"
          save: "pipeline"
  - key: "build_images"
    depends_on: "build_binaries"
    group: ":docker: Build images"
    steps:
      - label: ":package: engine"
        commands:
          - "buildkite-agent artifact download 'target/release/engine-app' ."
          - "docker build --no-cache -t ncn-engine:$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER -t ncn-engine:latest --build-arg=\"EXECUTABLE_FILE=engine-app\" ."
      - label: ":package: interactor"
        commands:
          - "buildkite-agent artifact download 'target/release/interactor-app' ."
          - "docker build -t ncn-interactor:$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER -t ncn-interactor:latest --build-arg=\"EXECUTABLE_FILE=interactor-app\" ."
      - label: ":package: registry"
        commands:
          - "buildkite-agent artifact download 'target/release/registry-app' ."
          - "docker build -t ncn-registry:$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER -t ncn-registry:latest --build-arg=\"EXECUTABLE_FILE=registry-app\" ."
      - label: ":package: simulator"
        commands:
          - "buildkite-agent artifact download 'target/release/simulator-app' ."
          - "docker build -t ncn-simulator:$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER -t ncn-simulator:latest --build-arg=\"EXECUTABLE_FILE=simulator-app\" ."
      - label: ":package: storage"
        commands:
          - "buildkite-agent artifact download 'target/release/storage-app' ."
          - "docker build -t ncn-storage:$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER -t ncn-storage:latest --build-arg=\"EXECUTABLE_FILE=storage-app\" ."
  - key: "prepare_sync"
    depends_on: "build_images"
    label: ":vertical_traffic_light:"
    commands:
      - "rclone mkdir drive:/Managed/Nucane/nucane/build/$BUILDKITE_BRANCH/$BUILDKITE_BUILD_NUMBER"
  - key: "upload_artifacts"
    depends_on: "prepare_sync"
    group: ":file_cabinet: $BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER"
    steps:
      - label: ":card_index_dividers: engine"
        commands:
          - "buildkite-agent artifact download 'target/release/engine-app' ."
          - "rclone sync ./target/release/engine-app drive:/Managed/Nucane/nucane/build/$BUILDKITE_BRANCH/$BUILDKITE_BUILD_NUMBER"
          - "docker save -o ./target/release/engine-$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER.tar ncn-engine:$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER"
          - "rclone sync ./target/release/engine-$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER.tar drive:/Managed/Nucane/nucane/build/$BUILDKITE_BRANCH/$BUILDKITE_BUILD_NUMBER"
      - label: ":card_index_dividers: interactor"
        commands:
          - "buildkite-agent artifact download 'target/release/interactor-app' ."
          - "rclone sync ./target/release/interactor-app drive:/Managed/Nucane/nucane/build/$BUILDKITE_BRANCH/$BUILDKITE_BUILD_NUMBER"
          - "docker save -o ./target/release/interactor-$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER.tar ncn-interactor:$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER"
          - "rclone sync ./target/release/interactor-$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER.tar drive:/Managed/Nucane/nucane/build/$BUILDKITE_BRANCH/$BUILDKITE_BUILD_NUMBER"
      - label: ":card_index_dividers: registry"
        commands:
          - "buildkite-agent artifact download 'target/release/registry-app' ."
          - "rclone sync ./target/release/registry-app drive:/Managed/Nucane/nucane/build/$BUILDKITE_BRANCH/$BUILDKITE_BUILD_NUMBER"
          - "docker save -o ./target/release/registry-$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER.tar ncn-registry:$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER"
          - "rclone sync ./target/release/registry-$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER.tar drive:/Managed/Nucane/nucane/build/$BUILDKITE_BRANCH/$BUILDKITE_BUILD_NUMBER"
      - label: ":card_index_dividers: simulator"
        commands:
          - "buildkite-agent artifact download 'target/release/simulator-app' ."
          - "rclone sync ./target/release/simulator-app drive:/Managed/Nucane/nucane/build/$BUILDKITE_BRANCH/$BUILDKITE_BUILD_NUMBER"
          - "docker save -o ./target/release/simulator-$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER.tar ncn-simulator:$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER"
          - "rclone sync ./target/release/simulator-$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER.tar drive:/Managed/Nucane/nucane/build/$BUILDKITE_BRANCH/$BUILDKITE_BUILD_NUMBER"
      - label: ":card_index_dividers: storage"
        commands:
          - "buildkite-agent artifact download 'target/release/storage-app' ."
          - "rclone sync ./target/release/storage-app drive:/Managed/Nucane/nucane/build/$BUILDKITE_BRANCH/$BUILDKITE_BUILD_NUMBER"
          - "docker save -o ./target/release/storage-$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER.tar ncn-storage:$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER"
          - "rclone sync ./target/release/storage-$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER.tar drive:/Managed/Nucane/nucane/build/$BUILDKITE_BRANCH/$BUILDKITE_BUILD_NUMBER"
