steps:
  - key: "check"
    label: ":mag: Check"
    commands:
        # todo fail on warnings "cargo clippy -- -D warnings"
      - "cargo clippy"
    plugins:
      - docker#v5.8.0:
          image: "rust-image"
  - key: "build"
    depends_on: "check"
    label: ":hammer_and_wrench: Build binaries"
    commands:
      - "cargo build --release"
      - "find ./target/release -type f \\( -name '.*' -or -name '*.d' -or -name '*.rlib' \\) -delete"
    artifact_paths:
      - "target/release/*"
    plugins:
      - docker#v5.8.0:
          image: "rust-image"
  - key: "test"
    depends_on: "build"
    allow_dependency_failure: true #todo remove
    label: ":clipboard: Test"
    commands:
      - "cargo nextest run"
    plugins:
      - docker#v5.8.0:
          image: "rust-image"
  - key: "build_images"
    depends_on: "build"
    group: ":docker: Build images"
    steps:
      - label: "registry"
        commands:
          - "buildkite-agent artifact download 'target/release/registry-app' ./"
          - "docker build -t registry:latest --build-arg=\"EXECUTABLE_NAME=registry-app\" ."
