steps:
  - key: "input"
    label: "Input"
    input: "Deploy params"
    fields:
      - key: "version"
        text: "Version"
        hint: "Value format '\\$BRANCH-\\$BUILD' or 'latest', get exact values from build pipeline"
        default: "latest"
      - key: "namespace"
        select: "Namespace"
        hint: "Namespace for deploy"
        options:
          - label: "dev"
            value: "dev"
          - label: "staging"
            value: "staging"
          - label: "prod"
            value: "prod"
        default: "dev"
      - key: "force"
        select: "Force"
        hint: "Be careful if this option 'true' existing namespace will be force deleted"
        options:
          - label: "true"
            value: "true"
          - label: "false"
            value: "false"
        default: "false"
  - key: "params"
    depends_on: "input"
    label: "Params"
    commands:
      - "VERSION=$(buildkite-agent meta-data get version) && echo \"VERSION: $$NAMESPACE\""
      - "NAMESPACE=$(buildkite-agent meta-data get namespace) && echo \"NAMESPACE: $$NAMESPACE\""
#  - key: "approve"
#    depends_on: "params"
#    label: "Approve"
#    block: "Approve force deploy"
#    if: "true"
  - key: "Deploy"
    depends_on: "approve"
    label: ":mag: Deploy"
    commands:
      - "docker compose up -d"
