steps:
  - key: "input"
    label: ":lower_left_crayon: Input"
    input: "Deploy params"
    fields:
      - key: "namespace"
        select: "Namespace"
        hint: "Namespace for deploy"
        options:
          - label: "dev"
            value: "dev"
          - label: "staging"
            value: "staging"
          - label: "prod"
            value: "prod"
        default: "dev"
      - key: "force"
        select: "Force"
        hint: "Be careful if this option 'true' existing namespace will be force deleted"
        options:
          - label: "true"
            value: "true"
          - label: "false"
            value: "false"
        default: "false"
      - key: "version"
        text: "Version"
        hint: "Value format '\\$BRANCH-\\$BUILD' or 'latest', get exact values from build pipeline"
        default: "latest"
      - key: "params"
        text: "Custom params"
        hint: "Custom environment parameters"
        default: |
          TS_AUTHKEY=
          DEMO=true
          OKX_API_KEY=
          OKX_API_PASSPHRASE=
          OKX_API_SECRET=
  - key: "Deploy"
    depends_on: "input"
    label: ":rocket: Deploy"
    commands:
      - "echo \"+++ :triangular_flag_on_post: PIPELINE PARAMS :triangular_flag_on_post:\""
      - "export NAMESPACE=$(buildkite-agent meta-data get namespace) && echo \"NAMESPACE: $$NAMESPACE\""
      - "export FORCE=$(buildkite-agent meta-data get force) && echo \"FORCE: $$FORCE\""
      - "export VERSION=$(buildkite-agent meta-data get version) && echo \"VERSION: $$VERSION\""
      - "echo \"+++ :triangular_flag_on_post: CUSTOM PARAMS :triangular_flag_on_post:\""
      - |
        while IFS= read -r line
                  do
                      echo "$$line"
                      export $$line
                  done <<< "$(buildkite-agent meta-data get params)"
      - "echo \"+++ :round_pushpin: COMPOSE FILE :round_pushpin:\""
      - "envsubst < docker-compose.yml"
      - "docker compose up"
