steps:
  - label: ":hammer: Build"
    commands:
      - "cargo build --release"
      - "ls"
#      - "sleep 120"
    artifact_paths: "target/release"
    plugins:
      - docker#v5.8.0:
          image: "rust-image"
