steps:
  - key: "check"
    label: ":mag: Check"
    commands:
        # fail on warnings "cargo clippy -- -D warnings"
      - "cargo clippy"
#    artifact_paths:
#      - "target/**"
    plugins:
      - docker#v5.8.0:
          image: "rust-image"
  - key: "build"
    depends_on: "check"
    label: ":hammer: Build"
    commands:
#      - "sleep 120"
#      - "buildkite-agent artifact download \"target/**\" ."
      - "cargo build --release"
    artifact_paths:
      - "target/**/*"
    plugins:
      - docker#v5.8.0:
          image: "rust-image"
#          mount-buildkite-agent: true
  - key: "test"
    depends_on: "build"
    label: ":clipboard: Test"
    commands:
#      - "buildkite-agent artifact download \"target/**\" ."
      - "cargo nextest run"
#    artifact_paths:
#      - "target/**"
    plugins:
      - docker#v5.8.0:
          image: "rust-image"
#          mount-buildkite-agent: true
