steps:
  - label: ":hammer: Build"
    command: sleep 120
#    artifact_paths: "./target/release"
    plugins:
      - docker#v5.8.0:
          image: "rust:latest"
          volumes:
            - ".:/app"
