steps:
  - key: "check"
    label: ":mag: Check"
    commands:
      - "cargo clippy -- -D warnings"
    plugins:
      - docker#v5.8.0:
          image: "rust-image"
  - key: "build"
    depends_on: "check"
    allow_dependency_failure: true #todo remove
    label: ":hammer_and_wrench: Build binaries"
    commands:
      - "cargo build --release"
      - "find ./target/release -type f \\( -name '.*' -or -name '*.d' -or -name '*.rlib' \\) -delete"
    artifact_paths:
      - "target/release/*"
    plugins:
      - docker#v5.8.0:
          image: "rust-image"
  - key: "test"
    depends_on: "build"
    label: ":clipboard: Test"
    commands:
      - "cargo nextest run"
    plugins:
      - docker#v5.8.0:
          image: "rust-image"
  - key: "build_images"
    depends_on: "build"
    group: ":docker: Build images"
    steps:
      - label: ":package: engine"
        commands:
          - "buildkite-agent artifact download 'target/release/engine-app' ."
          - "docker build -t ncn-engine:$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER --build-arg=\"EXECUTABLE_FILE=engine-app\" ."
      - label: ":package: interactor"
        commands:
          - "buildkite-agent artifact download 'target/release/interactor-app' ."
          - "docker build -t ncn-interactor:$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER --build-arg=\"EXECUTABLE_FILE=interactor-app\" ."
      - label: ":package: registry"
        commands:
          - "buildkite-agent artifact download 'target/release/registry-app' ."
          - "docker build -t ncn-registry:$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER --build-arg=\"EXECUTABLE_FILE=registry-app\" ."
      - label: ":package: simulator"
        commands:
          - "buildkite-agent artifact download 'target/release/simulator-app' ."
          - "docker build -t ncn-simulator:$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER --build-arg=\"EXECUTABLE_FILE=simulator-app\" ."
      - label: ":package: storage"
        commands:
          - "buildkite-agent artifact download 'target/release/storage-app' ."
          - "docker build -t ncn-storage:$BUILDKITE_BRANCH-$BUILDKITE_BUILD_NUMBER --build-arg=\"EXECUTABLE_FILE=storage-app\" ."
