steps:
  - label: ":hammer: Build"
    commands:
      - "cargo build --release"
      - "sleep 60"
    artifact_paths: "./target/release"
    plugins:
      - docker#v5.8.0:
          image: "rust:latest"
