steps:
  - key: "check"
    label: ":mag: Check"
    commands:
        # fail on warnings "cargo clippy -- -D warnings"
      - "cargo clippy"
    plugins:
      - docker#v5.8.0:
          image: "rust-image"
  - key: "build"
    depends_on: "check"
    label: ":hammer: Build"
    commands:
      - "cargo build --release"
    artifact_paths:
      - "target/release/*"
      - "!target/release/.*"
      - "!target/release/*.d"
      - "!target/release/*.rlib"
    plugins:
      - docker#v5.8.0:
          image: "rust-image"
  - key: "test"
    depends_on: "build"
    label: ":clipboard: Test"
    commands:
      - "cargo nextest run"
    plugins:
      - docker#v5.8.0:
          image: "rust-image"
