//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "order")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub id: String,
    pub timestamp: DateTimeUtc,
    #[sea_orm(column_type = "Binary(BlobSize::Blob(Some(16)))", nullable)]
    pub simulation_id: Option<Vec<u8>>,
    pub status: Json,
    pub exchange: String,
    pub pair: Json,
    pub market_type: Json,
    pub order_type: Json,
    pub side: String,
    #[sea_orm(column_type = "Double")]
    pub size: f64,
    #[sea_orm(column_type = "Double")]
    pub avg_price: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
