[package]
name = "storage-migration"
version = "1.0.0"
edition = "2021"
publish = false

[lib]
name = "storage_migration"
path = "src/lib.rs"

[dependencies]
async-std = { version = "1", features = ["attributes", "tokio1"] }

[dependencies.sea-orm-migration]
version = "0.11.0"
features = ["sqlx-mysql", "runtime-async-std-native-tls"]

