[package]
name = "storage-migration"
version.workspace = true
edition.workspace = true
publish = false

[lib]
name = "storage_migration"
path = "src/lib.rs"

[dependencies]
async-std = { workspace = true }
sea-orm-migration = { workspace = true }
