logging:
  level: INFO
  crates:
    simulator: DEBUG
application:
  name: simulator
  port: 8084
database.url: postgresql://postgres:root@localhost:5432
engine.url: localhost:8081
storage.url: localhost:8082
interactor.url: localhost:8083
