[package]
name = "storage-app"
version.workspace = true
edition.workspace = true

[dependencies]
synapse = { workspace = true }
interactor-rest-client = { workspace = true }
domain-model = { workspace = true }
storage-config = { workspace = true }
storage-migration = { workspace = true }
storage-core = { workspace = true }
storage-rest-api = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
axum = { workspace = true }
config = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
once_cell = { workspace = true }
uuid = { workspace = true }
futures = { workspace = true }
chrono = { workspace = true }
sea-orm = { workspace = true }
serde-inline-default = { workspace = true }
