[package]
name = "storage-rest-api"
version.workspace = true
edition.workspace = true

[dependencies]
domain-model = { workspace = true }
storage-core = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
