[package]
name = "registry-rest-api"
version = "0.1.0"
edition = "2021"

[dependencies]
registry-core = { path = "../core" }
uuid = { version = "1.3.2", features = ["v4", "serde"] }
serde = { verion = "1.0.162", features = ["derive", "serde_derive"] }
