logging:
  level: INFO
  crates:
    interactor: DEBUG
application:
  name: interactor
  port: 8083

eac:
  demo: true
  exchanges:
    okx:
      http:
        url: https://www.okx.com
      ws:
        url: wss://ws.okx.com:8443
      auth:
        key: # put value according to eac.demo value
        secret: # put value according to eac.demo value
        passphrase: # put value according to eac.demo value
        
broker.url: localhost:19092