logging:
  level: INFO
  crates:
    interactor: DEBUG
application:
  name: interactor
  port: 8083
storage.url: localhost:8082
engine.url: localhost:8081

eac:
  demo: true
  exchanges:
    bybit:
      http:
        url: # put value according to eac.demo value
      ws:
        url: # put value according to eac.demo value
      auth:
        key: # put value according to eac.demo value
        secret: # put value according to eac.demo value
    okx:
      http:
        url: https://www.okx.com
      ws:
        url: wss://ws.okx.com:8443
      auth:
        key: # put value according to eac.demo value
        secret: # put value according to eac.demo value
        passphrase: # put value according to eac.demo value
