logging:
  level: INFO
  crates:
    interactor: DEBUG
application:
  name: interactor
  port: 8083

eac:
  demo: true
  exchanges:
    okx:
      http_url: https://www.okx.com
      ws_url: wss://ws.okx.com:8443
      auth:
        api_key: # put value according to eac.demo value
        api_secret: # put value according to eac.demo value
        api_passphrase: # put value according to eac.demo value
