[package]
name = "massaging-api"
version.workspace = true
edition.workspace = true

[dependencies]
synapse = { workspace = true }
serde = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
anyhow = { workspace = true }
