[package]
name = "simulator-rest-client"
version.workspace = true
edition.workspace = true

[dependencies]
domain-model = { workspace = true }
simulator-core-api = { workspace = true }
simulator-rest-api = { workspace = true }
simulator-core = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_urlencoded = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
