[package]
name = "registry-rest-api-server"
version.workspace = true
edition.workspace = true

[dependencies]
registry-core-api = { workspace = true }
registry-rest-api = { workspace = true }
domain-model = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
uuid = { workspace = true }
chrono = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde-inline-default = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
once_cell = { workspace = true }
axum = { workspace = true }
