//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "simulation_report")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub simulation_id: Uuid,
    pub start: DateTime,
    pub end: DateTime,
    pub deployments: Json,
    pub ticks: i32,
    pub actions: i32,
    #[sea_orm(column_type = "Double")]
    pub profit: f64,
    #[sea_orm(column_type = "Double")]
    pub profit_clear: f64,
    #[sea_orm(column_type = "Double")]
    pub fees: f64,
    pub assets: Json,
    pub active_orders: Json,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
