[package]
name = "ui-core"
version.workspace = true
edition.workspace = true

[dependencies]
ui-core-api = { workspace = true }
domain-model = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
uuid = { workspace = true }
