[package]
name = "indicators-api"
version.workspace = true
edition.workspace = true

[dependencies]
domain-model = { workspace = true }
storage-core-api = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
