[package]
name = "engine-rest-client"
version.workspace = true
edition.workspace = true

[dependencies]
domain-model = { workspace = true }
engine-rest-api = { workspace = true }
engine-core-api = { workspace = true }
reqwest = { workspace = true }
tokio = { workspace = true }
anyhow = { workspace = true }
serde = { workspace = true }
serde_urlencoded = { workspace = true }
tracing = { workspace = true }
uuid = { workspace = true }
async-trait = { workspace = true }
