logging:
  level: INFO
  crates:
    storage: DEBUG
application:
  name: storage
  port: 8082
database.url: postgresql://postgres:root@localhost:5432
interactor.url: localhost:8083
broker.url: localhost:19092
